before_script:
  - apt-get update -qy || true
  - apt-get install -y python-dev python-pip zip || true

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_IMAGE: $CI_REGISTRY_USER/$CI_PROJECT_NAME

stages:
  - test
  - build

test:
  image: python:2
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m pylint --exit-zero app/app.py 


build:
  image: docker:latest
  stage: build
  script:
    - env
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD 
    - docker build  --tag $DOCKER_IMAGE:$CI_COMMIT_SHA --tag $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
    - docker push $DOCKER_IMAGE:latest
